import { useCallback, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '@xyflow/react/dist/style.css';
import './styles.css';
import { api, request, token, uid, download, InvalidContext, Field, JsonField, Select, ProviderField, Details, Status, type Json } from './shared';
import { Canvas, newNode, nodeKinds } from './canvas';
import { Inspector } from './inspector';
import { PackPanels } from './pack-panels';
import { RunPanel, rememberRun } from './run-panel';
function draft(): Json {
  const final = { ...newNode('agent','final'), role: 'finalizer', name: 'Main 验收', prompt_template: '审查上游产物和证据，明确接受后提交最终结果。' };
  return { schema_version: 1, id: uid('workflow'), name: '新 Workflow', description: '', enabled: true, status: 'draft', revision: 1, tags: [], inputs_schema: {}, outputs_schema: {},
    skill_policy: { mode: 'strict', implicit: 'deny', ambient_allow: [], shadowed_skill_paths: [] }, requirements: { providers: [], tools: [], mcp_servers: [], executables: [] }, finalization: { required: true, node_id: 'final' },
    nodes: [{ id: 'start', type: 'start', name: '开始' }, final, { id: 'end', type: 'end', name: '结束' }], edges: [{ id: 'start-final', source: 'start', target: 'final' }, { id: 'final-end', source: 'final', target: 'end' }] };
}
function App() {
  const [configuration, setConfiguration] = useState<Json | null>(null); const [library,setLibrary] = useState<Json[]>([]); const [runs,setRuns] = useState<Json[]>([]); const [capability,setCapability] = useState<Json | null>(null);
  const [pack,setPack] = useState<Json | null>(null); const [workflow,setWorkflow] = useState<Json | null>(null); const [dirty,setDirty] = useState(false); const [validation,setValidation] = useState<Json | null>(null);
  const [page,setPage] = useState('library'); const [tab,setTab] = useState('canvas'); const [selection,setSelection] = useState({ kind: 'workflow', id: '' }); const [runId,setRunId] = useState('');
  const [error,setError] = useState<Json | null>(null); const [busy,setBusy] = useState(0); const [invalid,setInvalid] = useState<Set<string>>(new Set());
  const [workspace,setWorkspace] = useState(''); const [inputs,setInputs] = useState<Json>({}); const [access,setAccess] = useState('read_only'); const [paths,setPaths] = useState<any>([]); const [approval,setApproval] = useState(false);
  const [inventory,setInventory] = useState<Json | null>(null); const [provider,setProvider] = useState(''); const [strict,setStrict] = useState<Json | null>(null); const [filter,setFilter] = useState('');
  const invalidChanged = useCallback((id: string, failed: boolean) => setInvalid(current => { const next = new Set(current); if (failed) next.add(id); else next.delete(id); return next; }), []);
  const act = useCallback((work: () => Promise<any>) => { setBusy(n => n + 1); setError(null); void work().catch(cause => setError({ message: cause.message, ...(cause.detail ?? {}) })).finally(() => setBusy(n => n - 1)); }, []);
  async function refreshLibrary() { setLibrary(await api('list')); }
  async function reload() {
    const config = await request('/api/config'); setConfiguration(config); setStrict(config.config.strict_executor ?? null);
    if (config.config.version === 7) { const values = await Promise.all([api('list'), api('runs'), api('capabilities')]); setLibrary(values[0]); setRuns(values[1]); setCapability(values[2]); }
  }
  useEffect(() => { act(reload); }, []);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  function mayLeave() { return !dirty || window.confirm('当前有未保存的草稿修改。放弃这些修改？'); }
  function change(next: Json) { setWorkflow({ ...next, status: 'draft' }); setDirty(true); setValidation(null); }
  async function saved(value: Json) { setPack(value); setWorkflow(value.workflow); setDirty(false); setValidation(await api('validate', { workflow: value.workflow })); await refreshLibrary(); }
  async function save() { if (invalid.size) throw new Error('请先修正 JSON 格式错误。'); if (!workflow) throw new Error('没有选中的 Workflow'); const value = await api(pack ? 'save' : 'create', { ...(pack ? { workflow_id: workflow.id, expected_revision: pack.revision_hash } : {}), workflow: { ...workflow, status: 'draft' } }); await saved(value); return value; }
  const providers = configuration?.config.providers ?? [];
  const openRun = (run: Json) => { setRunId(rememberRun(run)); setPage('run'); };
  const openPack = (id: string) => { if (mayLeave()) act(async () => { await saved(await api('read', { workflow_id: id })); setSelection({ kind: 'workflow', id: '' }); setTab('canvas'); setPage('editor'); }); };
  return <InvalidContext.Provider value={invalidChanged}><div className="app-shell" aria-busy={busy > 0}>
    <header className="topbar"><a className="brand" href={'/workflows#token=' + encodeURIComponent(token)} onClick={e => { e.preventDefault(); if (mayLeave()) setPage('library'); }}><span className="brand-mark">S</span><strong>Sol</strong><span>Workflow Studio</span></a><nav aria-label="工作区导航"><button className={page === 'library' ? 'active' : ''} onClick={() => { if (mayLeave()) { setPage('library'); act(refreshLibrary); } }}>流程库</button><button className={page === 'runs' || page === 'run' ? 'active' : ''} onClick={() => { if (mayLeave()) { setPage('runs'); act(async () => setRuns(await api('runs'))); } }}>运行记录</button><button className={page === 'settings' ? 'active' : ''} onClick={() => { if (mayLeave()) setPage('settings'); }}>执行能力</button><a href={'/#token=' + encodeURIComponent(token)} onClick={e => { if (!mayLeave()) e.preventDefault(); }}>Provider 设置 ↗</a></nav><span className="muted">{busy ? '正在处理…' : configuration ? '本地控制台' : '连接中…'}</span></header>
    {error && <div className="error-banner" role="alert"><div><strong>{error.code ?? '操作失败'}：{error.message}</strong><Details title="诊断详情" value={error}/></div><button aria-label="关闭错误" onClick={() => setError(null)}>×</button></div>}
    {invalid.size > 0 && <div className="notice" role="alert">存在无效 JSON，保存和发布已阻止。</div>}
    {configuration?.config.version === 6 ? <main className="landing"><span className="eyebrow">准备升级</span><h1>把阶段预设带入 Workflow</h1><p>迁移会保留固定 Provider、禁用状态、权限和审批要求，先创建备份，再一次性提交 v7 流程库。</p><p>当前配置：{configuration.storage?.config_path ?? '本地用户配置'}</p><button className="primary" disabled={busy > 0} onClick={() => act(async () => { await api('migrate_v6'); await reload(); })}>备份并迁移到 v7</button><Details title="当前配置修订" value={{ revision: configuration.revision }}/></main> : <>
    {page === 'library' && <main className="library-page scroll"><div className="page-heading"><div><span className="eyebrow">流程库</span><h1>让流程可以审查，也可以执行。</h1><p>从明确的步骤开始。每次运行固定完整版本，每个关键动作留下证据。</p></div><div className="actions"><button onClick={() => { if (mayLeave()) setPage('import'); }}>从 Skill 导入</button><button className="primary" onClick={() => { if (mayLeave()) { setPack(null); setWorkflow(draft()); setDirty(true); setSelection({ kind: 'workflow', id: '' }); setPage('editor'); setTab('canvas'); } }}>＋ 新建 Workflow</button></div></div>
      <Field label="搜索流程" value={filter} onChange={setFilter} placeholder="名称、说明或 ID"/>
      <div className="library-grid">{library.filter(item => `${item.name} ${item.id} ${item.description}`.toLowerCase().includes(filter.toLowerCase())).map(item => <button className="workflow-card" key={item.id} onClick={() => openPack(item.id)}><div className="card-meta"><span>{item.status === 'ready' ? 'READY' : 'DRAFT'}</span><span>{item.skill_policy.mode}</span></div><h2>{item.name}</h2><p>{item.description || '尚未添加说明'}</p><div className="card-footer"><span>{item.enabled ? '已启用' : '已禁用'}</span><span>{item.validation.launch_ready ? '◇ 定义可启动' : `${item.validation.errors.length} 个结构问题 · ${item.validation.blockers.length} 个阻塞`}</span></div></button>)}</div>{!library.length && <p>还没有 Workflow。新建一个，或将 Skill 导入为 Draft。</p>}
    </main>}
    {page === 'editor' && workflow && <div className="editor"><div className="editor-toolbar"><div><strong>{workflow.name}</strong><span className="muted">{dirty ? ' · 未保存' : ` · r${workflow.revision} · ${workflow.status}`}</span></div><div className="actions"><button disabled={!!invalid.size || busy > 0} onClick={() => act(async () => setValidation(await api('validate', { workflow })))}>校验</button><button disabled={!!invalid.size || busy > 0} onClick={() => act(save)}>保存 Draft</button><button className="primary" disabled={!!invalid.size || dirty || !pack || busy > 0} onClick={() => act(async () => saved(await api('publish', { workflow_id: workflow.id, expected_revision: pack?.revision_hash, reviewed: true })))}>确认所示版本并发布 Ready</button><button disabled={dirty || !pack || pack.workflow.status !== 'ready'} onClick={() => setTab('start')}>启动…</button></div></div>
      <div className="editor-tabs" role="tablist">{[['canvas','画布'],['resources','资源'],['review','导入审查'],['history','版本'],['json','完整 IR'],['start','运行设置']].map(([id,label]) => <button role="tab" aria-selected={tab === id} key={id} disabled={!pack && !['canvas','json'].includes(id)} onClick={() => { if (dirty && !['canvas','json'].includes(id)) { setError({ message: '请先保存草稿，再操作其固定资源和版本。' }); return; } setTab(id); }}>{label}</button>)}<span className="spacer"/>{pack && <><button onClick={() => act(async () => download(workflow.id + '.workflow.json', await api('export', { workflow_id: workflow.id, revision_hash: pack.revision_hash })))}>导出 Pack</button><button disabled={dirty} onClick={() => act(async () => saved(await api('duplicate', { workflow_id: workflow.id, revision_hash: pack.revision_hash, new_id: uid(workflow.id.slice(0,30)), name: workflow.name + ' 副本' })))}>复制</button><button className="danger" disabled={dirty} onClick={() => { if (window.confirm('将此 Workflow 移入可恢复存储？历史 Run 不受影响。')) act(async () => { await api('delete', { workflow_id: workflow.id, expected_revision: pack.revision_hash }); setPack(null); setWorkflow(null); setPage('library'); await refreshLibrary(); }); }}>删除</button></>}</div>
      {validation && <div className={'validation-bar ' + (validation.valid ? '' : 'invalid')}><strong>{validation.valid ? '✓ 结构有效' : '× 结构无效'}</strong><span>{validation.launch_ready ? '定义检查通过；启动时复核执行能力和权限' : '当前启动有阻塞'}</span><details><summary>{validation.errors.length + validation.blockers.length} 条诊断</summary>{[...validation.errors, ...validation.blockers].map((issue: Json,index: number) => <button key={index} onClick={() => { setTab('canvas'); setSelection({ kind: issue.node_id ? 'node' : issue.edge_id ? 'edge' : 'workflow', id: issue.node_id ?? issue.edge_id ?? '' }); }}>{issue.code} · {issue.node_id ?? issue.edge_id ?? ''} · {issue.message}</button>)}</details></div>}
      {tab === 'canvas' && <div className="editor-body"><aside className="palette scroll"><h2>节点</h2><p>拖入画布，或点击添加。</p>{nodeKinds.map(kind => <button draggable key={kind} onDragStart={e => { e.dataTransfer.setData('application/sol-node',kind); e.dataTransfer.effectAllowed = 'move'; }} onClick={() => { const node = newNode(kind); change({ ...workflow, nodes: [...workflow.nodes,node] }); setSelection({ kind: 'node', id: node.id }); }}>{kind}<span>＋</span></button>)}<p>从连接点拖动创建边。点击节点或连线编辑属性。</p></aside><Canvas workflow={workflow} onChange={change} onSelect={(kind,id) => setSelection({ kind,id })}/><Inspector key={selection.kind + selection.id} workflow={workflow} selection={selection} providers={providers} change={change} select={(kind,id) => setSelection({ kind,id })} inline={() => act(async () => { if (dirty || !pack) throw new Error('请先保存精确 SkillRef 版本。'); await saved(await api('inline_skill', { workflow_id: workflow.id, node_id: selection.id, expected_revision: pack.revision_hash })); })}/></div>}
      {['resources','history','review'].includes(tab) && pack && <PackPanels pack={pack} tab={tab} saved={saved} act={act} providers={providers} openRun={openRun} workspace={workspace}/>}
      {tab === 'json' && <section className="detail-page scroll"><h2>完整 Workflow IR</h2><p>未知领域字段会原样保留。此处可编辑可视属性表未覆盖的扩展字段；保存前由后端检查。</p><JsonField label="Workflow JSON" value={workflow} onChange={value => { if (!value || !Array.isArray(value.nodes) || !Array.isArray(value.edges) || !value.skill_policy || !value.finalization) throw new Error('IR 缺少节点、连接、Skill 策略或最终验收字段'); change(value); }} rows={28}/></section>}
      {tab === 'start' && <section className="detail-page scroll"><h2>启动固定版本</h2><p>工作区与路径范围只授权本次 Run。模型、Provider、Skill 和资源版本会完整固定。</p><Field label="工作区绝对路径" value={workspace} onChange={setWorkspace}/><Select label="本次最大访问权限" value={access} onChange={setAccess} options={['read_only','bounded_write']}/><JsonField label="允许写入的相对路径范围（非 glob）" value={paths} onChange={setPaths}/><JsonField label="输入" value={inputs} onChange={setInputs}/><label className="check"><input type="checkbox" checked={approval} onChange={e => setApproval(e.target.checked)}/>每个执行节点需批准</label><button className="primary" disabled={!workspace || dirty || pack?.workflow.status !== 'ready' || !!invalid.size || busy > 0} onClick={() => act(async () => openRun(await api('start', { workflow_id: workflow.id, revision_hash: pack?.revision_hash, workspace, inputs, access, allowed_paths: paths, require_approval: approval, main_actor: 'human-console' })))}>启动此版本</button><Details title="当前执行能力" value={capability}/></section>}
    </div>}
    {page === 'import' && <main className="detail-page scroll"><span className="eyebrow">单向导入</span><h1>从 Skill 创建 Draft</h1><p>从实际 Codex 目录中选取 Skill。导入保留来源和资源，脚本与外部依赖会明确列出。</p><Field label="发现 Skill 的工作区绝对路径" value={workspace} onChange={setWorkspace}/><ProviderField providers={providers} value={provider} onChange={setProvider}/><button disabled={!workspace || busy > 0} onClick={() => act(async () => setInventory(await api('skill_inventory', { workspace })))}>读取实际 Skill 清单</button>{inventory && <><Details title="发现范围与错误" value={{ ...inventory, entries: undefined }}/>{inventory.entries.map((item: Json) => <article className="history-row" key={item.id}><div><strong>{item.name}</strong><p>{item.path}</p><small>{item.source_hash}</small></div><button disabled={!provider || busy > 0} onClick={() => act(async () => { await saved(await api('import_skill', { workspace, skill_id: item.id, workflow_id: uid('import'), ...(provider === '$main' ? {} : { provider_id: provider }) })); setPage('editor'); setTab('review'); })}>导入此版本</button></article>)}</>}</main>}
    {page === 'settings' && <main className="detail-page scroll"><h1>执行能力</h1><p>Strict 约束已验证的目录、显式 Skill 输入与工具代理。具体系统及二进制必须通过资格检查。</p><Details title="当前资格、限制和诊断" value={capability}/>{strict && <><label className="check"><input type="checkbox" checked={strict.enabled} onChange={e => setStrict({ ...strict, enabled: e.target.checked })}/>启用已验证的 Strict 执行器</label><Field label="Codex 可执行文件绝对路径" value={strict.codex_binary} onChange={codex_binary => setStrict({ ...strict, codex_binary })}/><Field label="已验证二进制 SHA-256" value={strict.binary_sha256} onChange={binary_sha256 => setStrict({ ...strict, binary_sha256 })}/><Select label="认证模式" value={strict.authentication.mode} options={['managed_chatgpt','environment_api_key']} onChange={mode => setStrict({ ...strict, authentication: { ...strict.authentication, mode } })}/>{strict.authentication.mode === 'environment_api_key' && <Field label="API Key 环境变量名（只填名称）" value={strict.authentication.api_key_env} onChange={api_key_env => setStrict({ ...strict, authentication: { ...strict.authentication, api_key_env } })}/>}<Select label="Main 提案模型" value={strict.main_model} options={['gpt-5.6-sol','gpt-5.6-terra']} onChange={main_model => setStrict({ ...strict, main_model })}/><Select label="Main 推理强度" value={strict.main_reasoning_effort} options={['high','xhigh','max']} onChange={main_reasoning_effort => setStrict({ ...strict, main_reasoning_effort })}/><button disabled={busy > 0} onClick={() => act(async () => { await request('/api/config', { config: { ...configuration?.config, strict_executor: strict }, expected_revision: configuration?.revision }, 'PUT'); await reload(); })}>保存明确的执行器设置</button></>}</main>}
    {page === 'runs' && <main className="library-page scroll"><div className="page-heading"><div><span className="eyebrow">运行记录</span><h1>状态来自实际运行日志。</h1></div><button onClick={() => act(async () => setRuns(await api('runs')))}>刷新</button></div>{runs.map(run => <button className="run-row" key={run.run_id} onClick={() => { setRunId(run.run_id); setPage('run'); }}><strong>{run.workflow_id ?? run.run_id}</strong><Status value={run.status}/><code>{run.run_id}</code><span>{run.updated_at}</span></button>)}{!runs.length && <p>还没有运行记录。</p>}</main>}
    {page === 'run' && <RunPanel key={runId} runId={runId} act={act} onRun={id => setRunId(id)}/>}
    </>}
  </div></InvalidContext.Provider>;
}
createRoot(document.getElementById('root')!).render(<App/>);
