const string = { type: 'string' }; const object = { type: 'object' };
const properties = {
  workflow_id: string, revision_hash: string, run_id: string, node_id: string, attempt_id: string,
  control_token: { type: 'string', description: 'Main-controller capability returned by workflow_start. Never include it in worker prompts.' },
  lease_token: { type: 'string', description: 'Exact attempt lease returned by workflow_claim_node.' },
  request_id: string, owner: string, expected_sequence: { type: 'integer', minimum: 1 },
  expected_revision: string, workflow: object, resources: object, inputs: {}, workspace: string,
  access: { type: 'string', enum: ['read_only', 'bounded_write'] }, allowed_paths: { type: 'array', items: string },
  constraints: {}, main_actor: string, require_approval: { type: 'boolean' }, completion: object, error: object,
  reconciliation: object, after_restart: { type: 'boolean' }, reason: string, approval_id: string, decision: { type: 'boolean' },
  after_sequence: { type: 'integer', minimum: 0 }, receipt: object,
  skill_id: string, provider_id: string, name: string, proposal: object, accepted: { type: 'boolean' },
  region_id: string, patch_sha256: string,
  resource_path: string, text: string, remove: { type: 'boolean' },
  control: object,
};
const lease = ['run_id', 'node_id', 'attempt_id', 'lease_token'];
const main = ['run_id', 'control_token'];
const recovery = [...main, 'node_id', 'attempt_id'];
const specs = [
  ['capabilities', 'Read current Strict qualification and declared host capabilities without starting a session or exposing credentials.', [], []],
  ['skill_inventory', 'Read actual host Skill metadata and per-path discovery errors. Never treats a filesystem guess as complete discovery.', ['workspace'], []],
  ['import_skill', 'Coarse-import a user-selected current Skill inventory entry into an immutable Strict Draft. Executes no scripts or model calls.', ['workspace', 'skill_id', 'workflow_id'], ['name', 'provider_id']],
  ['verify_relocation', 'Verify pinned imported resource availability without reading the original Skill. Does not prove functional execution.', ['workflow_id', 'revision_hash'], []],
  ['import_review', 'Read unresolved import observations and exact inferred nodes/edges for human review. This does not confirm or publish them.', ['workflow_id'], ['revision_hash']],
  ['inline_skill', 'Convert one exact SkillRef and its explicitly pinned nested Skills to editable resource-backed instructions. Always creates a Draft and never runs source scripts.', ['workflow_id', 'node_id', 'expected_revision'], []],
  ['prepare_expansion', 'Prepare a read-only expansion packet for the user-selected Provider. This does not invoke that Provider or grant approval.', ['workflow_id', 'revision_hash', 'provider_id'], []],
  ['apply_expansion', 'Validate an inferred graph against its exact coarse revision and save another Draft. Never changes Provider/write/finalizer authority.', ['workflow_id', 'expected_revision', 'proposal'], []],
  ['create_expansion_run', 'Create a read-only Strict planning Run using the user-selected native Provider. Use normal claim/dispatch/collect operations; its source Draft is unchanged.', ['workflow_id', 'revision_hash', 'provider_id', 'run_id', 'workspace', 'main_actor'], []],
  ['apply_expansion_result', 'Apply a main-accepted planning Run to its exact source revision as an unreviewed Draft. Never dispatches or retries a model.', [...main, 'workflow_id', 'expected_revision'], []],
  ['list', 'List Workflow metadata and structural/environment readiness, without prompt bodies.', [], []],
  ['read', 'Read one explicit immutable Workflow revision for inspection or editing.', ['workflow_id'], ['revision_hash']],
  ['source_status', 'Compare explicitly pinned Skill instruction source hashes and report update_available or read diagnostics. Never changes Workflow resources or an existing Run.', ['workflow_id'], ['revision_hash']],
  ['revisions', 'Read immutable revision history metadata. Opening a revision verifies its resource content separately.', ['workflow_id'], []],
  ['read_resource', 'Read an exact pinned Pack resource for inspection. Binary or large content is not editable as text.', ['workflow_id', 'resource_path'], ['revision_hash']],
  ['write_resource', 'Save one user-requested bounded resource edit as a Draft under revision CAS. Imported resource changes require review and never touch the original source.', ['workflow_id', 'expected_revision', 'resource_path'], ['text', 'remove']],
  ['validate', 'Validate a graph, pinned bindings and current launch blockers.', ['workflow'], []],
  ['create', 'Create a user-requested Workflow Pack as Draft. Imported Skill drafts remain Strict; Ready publication belongs to the human console.', ['workflow'], ['resources']],
  ['save', 'Save one complete Draft definition using the previously read revision hash. Model edits cannot publish Ready.', ['workflow_id', 'workflow', 'expected_revision'], ['resources']],
  ['start', 'Start one Ready Workflow with explicit workspace permissions. Preserve control_token only in the main controller. No implicit Provider fallback or Strict downgrade.', ['workflow_id', 'workspace', 'access', 'main_actor'], ['revision_hash', 'run_id', 'inputs', 'allowed_paths', 'constraints', 'require_approval']],
  ['runs', 'List persisted Run metadata.', [], []],
  ['get', 'Read the current state reconstructed from the authoritative Run journal.', ['run_id'], []],
  ['run_definition', 'Read the Run-pinned Workflow definition even after its library revision is edited or deleted.', ['run_id'], []],
  ['node_details', 'Read the exact pinned Provider and backend-computed node permission and Skill policy boundary.', ['run_id','node_id'], []],
  ['recover_claim', 'Recover an interrupted claim only if no dispatch intent exists. Rotates its lease without a new attempt or retry charge.', recovery, []],
  ['reattach_connector', 'Verify and reattach the exact persisted connector task. Never selects latest, submits a new task or charges a retry.', recovery, []],
  ['reattach_handoff', 'After the main host inspects its exact native/MCP task, attest its unchanged recorded receipt and actual active/completed evidence. This is host attestation, not independent connector verification. No resubmission or retry charge.', recovery, ['reconciliation']],
  ['control_connector', 'Control only this attempt’s exact connector task. Permission/input responses require actual user authorization and the returned exact request/options. Cancellation remains pending until confirmed remotely.', [...lease, 'control_token', 'control'], []],
  ['recover_strict_result', 'Recover only a hash-pinned Strict result with recorded session shutdown; no model turn is resumed or submitted.', recovery, []],
  ['reattach_subworkflow', 'Reattach the existing pinned child Run and rotate the parent lease without recreating either Run.', recovery, []],
  ['child_control', 'Return the exact existing child main-controller capability to its authorized parent controller. Never put it in worker prompts.', recovery, []],
  ['next', 'Read ready node IDs and pending approvals. This does not claim or dispatch work.', ['run_id'], []],
  ['claim_node', 'Atomically claim one ready node and return its narrow execution lease. Main nodes require the exact main actor.', [...main, 'node_id', 'owner', 'request_id'], ['expected_sequence']],
  ['complete_node', 'Commit successful node output plus artifacts, evidence, changed_paths and outside_paths. Final acceptance requires main authority.', [...lease, 'completion'], []],
  ['fail_node', 'Commit an explicit node failure diagnostic under its active lease.', [...lease, 'error'], []],
  ['retry_node', 'Explicitly retry a failed/interrupted node within its pinned budget. Uncertain external dispatch requires reconciliation evidence.', [...main, 'node_id'], ['reconciliation']],
  ['pause', 'Pause new node release and dispatch; active completions remain recorded.', main, ['reason']],
  ['resume', 'Resume a paused Run, or fence and reconstruct it after_restart. Never silently resubmits an interrupted task.', main, ['after_restart']],
  ['cancel', 'Fence local Run leases and mark external cancellation pending. Remote termination must be confirmed separately.', main, []],
  ['approve', 'Record an authorized current-node approval bound to the pinned scope. Set decision only from actual user authorization.', [...main, 'approval_id', 'decision'], []],
  ['events', 'Read sequenced event metadata without prompts or controller secrets.', main, ['after_sequence']],
  ['dispatch', 'Persist intent, then invoke the pinned built-in/API Provider or return a main/native/MCP handoff. Repeated uncertain dispatch never resubmits.', [...lease, 'control_token'], []],
  ['dispatch_receipt', 'Persist exact task identity from the external tool result for one existing dispatch intent.', [...lease, 'control_token', 'request_id', 'receipt'], []],
  ['reconcile_connector', 'Inspect only the preallocated exact connector task after an uncertain dispatch. Does not retry it.', [...lease, 'control_token'], []],
  ['collect_connector', 'Collect an active exact connector task. Commit completion only with observed terminal and workspace-scope evidence.', [...lease, 'control_token'], []],
  ['collect_subworkflow', 'Collect the exact child Run after its main-agent acceptance. Output stays in the parent node namespace; collection never invokes another executor.', [...lease, 'control_token'], []],
  ['prepare_integration', 'Verify isolated branch changes and create an immutable merge proposal after Join. Conflicts or failed branches stop integration.', [...main, 'region_id'], []],
  ['review_integration', 'Read the exact saved merge patch and branch evidence before main-controlled integration.', [...main, 'region_id'], []],
  ['integrate_parallel', 'Apply a main-reviewed exact merge patch only if its target still matches the recorded base. Leaves the user branch and index unchanged.', [...main, 'region_id', 'accepted', 'patch_sha256'], []],
  ['cleanup_parallel', 'Remove exact owned worktrees only after terminal execution and accepted unchanged branch snapshots. Unmerged or changed worktrees remain for inspection.', main, []],
  ['strict_status', 'Read one exact isolated session status. Login URLs are restricted to the human console.', [...lease, 'control_token'], []],
  ['collect_strict', 'Read or reconcile a durable isolated result without another model submission. Finalization requires explicit main-controller acceptance.', [...lease, 'control_token'], ['accepted']],
  ['cleanup_strict_orphans', 'After fencing an interrupted attempt, stop and remove only its verified orphan profile. Never resubmits work or terminates an active owner.', [...lease, 'control_token'], []],
];
export const WORKFLOW_TOOL_OPERATIONS = new Set(specs.map(([name]) => name));
export function workflowToolDefinitions() {
  return specs.map(([name, description, required, optional]) => ({ name: 'workflow_' + name, description,
    inputSchema: { type: 'object', properties: Object.fromEntries([...required, ...optional].map(key => [key, properties[key]])), required, additionalProperties: false },
  }));
}
